// <auto-generated />
using System;
using FoodDeliveryrestart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDeliveryrestart.Migrations
{
    [DbContext(typeof(FoodDeliveryrestartContext))]
    [Migration("20260115170116_SeedMenuItems")]
    partial class SeedMenuItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c1a2b3c4-d5e6-4789-8901-234567890abc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "36e0ecf4-17bf-47a5-9652-ea6de371e64c",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFb0At0CjHXrRb/v9WoIkPefhjOSb/j5J/TuBbe+s36ESPQiMyw42u0jz/d2JO0J4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "faecefda-7a90-440a-a4c1-8f41ddeecf88",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MallId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MallId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupOrder");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrderMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupOrderMember");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Mall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MallName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mall");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "4 Tampines Central 5, Singapore 529510",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3347),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3356),
                            MallName = "Tampines Mall",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1 HarbourFront Walk, Singapore 098585",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3357),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3357),
                            MallName = "Vivo City",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Address = "181 Orchard Rd, Singapore 238896",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3359),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3359),
                            MallName = "Orchard Central",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3597),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3597),
                            Description = "Signature burger topped with mozzarella and onions.",
                            ItemName = "Mozza Burger",
                            NutritionInfo = "Approx. 650 kcal",
                            Price = 9.40m,
                            RestaurantId = 1,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3599),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3600),
                            Description = "Hot dog topped with savory coney sauce.",
                            ItemName = "Coney Dog",
                            NutritionInfo = "Approx. 420 kcal",
                            Price = 6.60m,
                            RestaurantId = 1,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3601),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3602),
                            Description = "Crispy curly fries, perfect for sharing.",
                            ItemName = "Curly Fries",
                            NutritionInfo = "Approx. 360 kcal",
                            Price = 3.60m,
                            RestaurantId = 1,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3604),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3604),
                            Description = "Classic root beer with vanilla ice cream.",
                            ItemName = "Root Beer Float",
                            NutritionInfo = "Approx. 380 kcal",
                            Price = 3.50m,
                            RestaurantId = 1,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3606),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3607),
                            Description = "Juicy beef patty with house sauce and fresh veg.",
                            ItemName = "Basic Burger",
                            NutritionInfo = "Approx. 750 kcal",
                            Price = 20.50m,
                            RestaurantId = 2,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3609),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3609),
                            Description = "Crispy fish fillet with tartar sauce.",
                            ItemName = "Fish Burger",
                            NutritionInfo = "Approx. 620 kcal",
                            Price = 17.80m,
                            RestaurantId = 2,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3611),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3611),
                            Description = "Golden battered onion rings.",
                            ItemName = "Onion Rings",
                            NutritionInfo = "Approx. 410 kcal",
                            Price = 6.80m,
                            RestaurantId = 2,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3613),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3614),
                            Description = "Fries tossed with truffle oil and seasoning.",
                            ItemName = "Truffle Fries",
                            NutritionInfo = "Approx. 520 kcal",
                            Price = 8.00m,
                            RestaurantId = 2,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3615),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3616),
                            Description = "Crispy fried chicken with gravy.",
                            ItemName = "Chickenjoy (1pc)",
                            NutritionInfo = "Approx. 480 kcal",
                            Price = 5.70m,
                            RestaurantId = 3,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3618),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3618),
                            Description = "Sweet-style spaghetti with hotdog slices.",
                            ItemName = "Jolly Spaghetti",
                            NutritionInfo = "Approx. 560 kcal",
                            Price = 6.50m,
                            RestaurantId = 3,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3620),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3621),
                            Description = "Classic burger with Jollibee signature dressing.",
                            ItemName = "Yumburger",
                            NutritionInfo = "Approx. 390 kcal",
                            Price = 3.90m,
                            RestaurantId = 3,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3622),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3623),
                            Description = "Crispy pie filled with peach-mango goodness.",
                            ItemName = "Peach Mango Pie",
                            NutritionInfo = "Approx. 260 kcal",
                            Price = 1.90m,
                            RestaurantId = 3,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3625),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3625),
                            Description = "KFC signature chicken with 11 herbs & spices.",
                            ItemName = "Original Recipe Chicken (1pc)",
                            NutritionInfo = "Approx. 320 kcal",
                            Price = 4.45m,
                            RestaurantId = 4,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3627),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3627),
                            Description = "Spicy chicken fillet burger with mayo.",
                            ItemName = "Zinger Burger",
                            NutritionInfo = "Approx. 550 kcal",
                            Price = 7.50m,
                            RestaurantId = 4,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3629),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3630),
                            Description = "Fries topped with warm cheese sauce.",
                            ItemName = "Cheese Fries",
                            NutritionInfo = "Approx. 460 kcal",
                            Price = 4.50m,
                            RestaurantId = 4,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3632),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3632),
                            Description = "Bite-sized chicken chunks, crispy and juicy.",
                            ItemName = "Popcorn Chicken",
                            NutritionInfo = "Approx. 430 kcal",
                            Price = 5.50m,
                            RestaurantId = 4,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3670),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3670),
                            Description = "Two beef patties with special sauce and lettuce.",
                            ItemName = "Big Mac",
                            NutritionInfo = "Approx. 540 kcal",
                            Price = 7.60m,
                            RestaurantId = 5,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3672),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3673),
                            Description = "Spicy chicken burger with lettuce and mayo.",
                            ItemName = "McSpicy",
                            NutritionInfo = "Approx. 560 kcal",
                            Price = 7.50m,
                            RestaurantId = 5,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3674),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3675),
                            Description = "Fish patty with tartar sauce and cheese.",
                            ItemName = "Filet-O-Fish",
                            NutritionInfo = "Approx. 390 kcal",
                            Price = 7.45m,
                            RestaurantId = 5,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3677),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3677),
                            Description = "Crispy pastry filled with warm apple cinnamon.",
                            ItemName = "Apple Pie",
                            NutritionInfo = "Approx. 240 kcal",
                            Price = 2.50m,
                            RestaurantId = 5,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3679),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3680),
                            Description = "Creamy pasta with bacon and parmesan.",
                            ItemName = "Carbonara",
                            NutritionInfo = "Approx. 720 kcal",
                            Price = 14.90m,
                            RestaurantId = 6,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3681),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3682),
                            Description = "Garlic, olive oil, chili flakes, and parsley.",
                            ItemName = "Aglio Olio",
                            NutritionInfo = "Approx. 620 kcal",
                            Price = 12.90m,
                            RestaurantId = 6,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3684),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3684),
                            Description = "Slow-cooked beef ragu with pasta.",
                            ItemName = "Beef Bolognese",
                            NutritionInfo = "Approx. 740 kcal",
                            Price = 16.90m,
                            RestaurantId = 6,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3686),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3687),
                            Description = "Layered pasta baked with meat sauce and cheese.",
                            ItemName = "Lasagna",
                            NutritionInfo = "Approx. 850 kcal",
                            Price = 18.90m,
                            RestaurantId = 6,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3688),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3689),
                            Description = "Tomato sauce, mozzarella, basil.",
                            ItemName = "Margherita Pizza",
                            NutritionInfo = "Approx. 780 kcal",
                            Price = 12.90m,
                            RestaurantId = 7,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3691),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3691),
                            Description = "Pepperoni, mozzarella, tomato base.",
                            ItemName = "Pepperoni Pizza",
                            NutritionInfo = "Approx. 920 kcal",
                            Price = 14.90m,
                            RestaurantId = 7,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3693),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3694),
                            Description = "Ham and pineapple with mozzarella.",
                            ItemName = "Hawaiian Pizza",
                            NutritionInfo = "Approx. 880 kcal",
                            Price = 14.50m,
                            RestaurantId = 7,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3695),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3696),
                            Description = "Toasted garlic bread slices.",
                            ItemName = "Garlic Bread",
                            NutritionInfo = "Approx. 420 kcal",
                            Price = 5.50m,
                            RestaurantId = 7,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3698),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3698),
                            Description = "Thai-style fried rice with prawn and pineapple.",
                            ItemName = "Pineapple Fried Rice (Prawn)",
                            NutritionInfo = "Approx. 680 kcal",
                            Price = 9.48m,
                            RestaurantId = 8,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3700),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3700),
                            Description = "Creamy tom yum with seafood and herbs.",
                            ItemName = "Creamy Tom Yum Soup (Seafood)",
                            NutritionInfo = "Approx. 420 kcal",
                            Price = 12.90m,
                            RestaurantId = 8,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3702),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3703),
                            Description = "Stir-fried Thai noodles with prawn.",
                            ItemName = "Pad Thai (Prawn)",
                            NutritionInfo = "Approx. 700 kcal",
                            Price = 10.90m,
                            RestaurantId = 8,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3705),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3705),
                            Description = "Basil chicken served with fragrant rice.",
                            ItemName = "Thai Basil Chicken Rice",
                            NutritionInfo = "Approx. 640 kcal",
                            Price = 9.40m,
                            RestaurantId = 8,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3707),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3707),
                            Description = "Classic tart froyo cup (choose toppings).",
                            ItemName = "Signature Tart Frozen Yogurt Cup",
                            NutritionInfo = "Approx. 280 kcal (base)",
                            Price = 7.90m,
                            RestaurantId = 9,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3709),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3710),
                            Description = "Creamy froyo with cookies flavour.",
                            ItemName = "Cookies & Cream Frozen Yogurt Cup",
                            NutritionInfo = "Approx. 320 kcal (base)",
                            Price = 8.50m,
                            RestaurantId = 9,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3712),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3712),
                            Description = "Add Biscoff spread as topping.",
                            ItemName = "Biscoff Spread Topping",
                            NutritionInfo = "Approx. 90 kcal",
                            Price = 1.50m,
                            RestaurantId = 9,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3714),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3714),
                            Description = "Add chocolate brownie as topping.",
                            ItemName = "Chocolate Fudge Brownie Topping",
                            NutritionInfo = "Approx. 140 kcal",
                            Price = 1.80m,
                            RestaurantId = 9,
                            UpdatedBy = "Seed"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardHolderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CardType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardHolderName = "Seed User",
                            CardType = "Visa",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 15, 17, 1, 15, 600, DateTimeKind.Utc).AddTicks(3223),
                            DateUpdated = new DateTime(2026, 1, 15, 17, 1, 15, 600, DateTimeKind.Utc).AddTicks(3223),
                            ExpiryMonth = 12,
                            ExpiryYear = 2026,
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CardHolderName = "Seed User",
                            CardType = "MasterCard",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 15, 17, 1, 15, 600, DateTimeKind.Utc).AddTicks(3225),
                            DateUpdated = new DateTime(2026, 1, 15, 17, 1, 15, 600, DateTimeKind.Utc).AddTicks(3226),
                            ExpiryMonth = 10,
                            ExpiryYear = 2025,
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CardHolderName = "Seed User",
                            CardType = "AMEX",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 15, 17, 1, 15, 600, DateTimeKind.Utc).AddTicks(3227),
                            DateUpdated = new DateTime(2026, 1, 15, 17, 1, 15, 600, DateTimeKind.Utc).AddTicks(3228),
                            ExpiryMonth = 6,
                            ExpiryYear = 2027,
                            UpdatedBy = "System",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusyLevel")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuisineType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationWithinMall")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MallId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperatingHours")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MallId");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusyLevel = 1,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3464),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3465),
                            LocationWithinMall = "1-24",
                            MallId = 1,
                            Name = "A&W",
                            OperatingHours = "10am-10pm",
                            Rating = 4.4m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 2,
                            BusyLevel = 2,
                            CreatedBy = "Seed",
                            CuisineType = "Western",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3467),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3468),
                            LocationWithinMall = "1-68",
                            MallId = 1,
                            Name = "Burger Lab",
                            OperatingHours = "10am-10pm",
                            Rating = 4.6m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 3,
                            BusyLevel = 1,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3470),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3470),
                            LocationWithinMall = "8-90",
                            MallId = 1,
                            Name = "Jollibee",
                            OperatingHours = "10am-10pm",
                            Rating = 4.7m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 4,
                            BusyLevel = 2,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3472),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3473),
                            LocationWithinMall = "8-89",
                            MallId = 1,
                            Name = "KFC",
                            OperatingHours = "24/7",
                            Rating = 4.2m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 5,
                            BusyLevel = 2,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3475),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3475),
                            LocationWithinMall = "8-88",
                            MallId = 1,
                            Name = "McDonald's",
                            OperatingHours = "24/7",
                            Rating = 4.3m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 6,
                            BusyLevel = 0,
                            CreatedBy = "Seed",
                            CuisineType = "Western",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3477),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3477),
                            LocationWithinMall = "1-67",
                            MallId = 1,
                            Name = "Pasta Corner",
                            OperatingHours = "24/7",
                            Rating = 4.1m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 7,
                            BusyLevel = 1,
                            CreatedBy = "Seed",
                            CuisineType = "Western Food",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3480),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3480),
                            LocationWithinMall = "1-66",
                            MallId = 1,
                            Name = "Pizza House",
                            OperatingHours = "24/7",
                            Rating = 4.5m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 8,
                            BusyLevel = 1,
                            CreatedBy = "Seed",
                            CuisineType = "Thai Food",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3482),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3482),
                            LocationWithinMall = "1-25",
                            MallId = 1,
                            Name = "Sanook Kitchen",
                            OperatingHours = "10am-10pm",
                            Rating = 4.6m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 9,
                            BusyLevel = 0,
                            CreatedBy = "Seed",
                            CuisineType = "Dessert",
                            DateCreated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3484),
                            DateUpdated = new DateTime(2026, 1, 16, 1, 1, 15, 600, DateTimeKind.Local).AddTicks(3485),
                            LocationWithinMall = "1-23",
                            MallId = 1,
                            Name = "Yochi",
                            OperatingHours = "10am-10pm",
                            Rating = 4.8m,
                            UpdatedBy = "Seed"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 15, 17, 1, 15, 600, DateTimeKind.Utc).AddTicks(2179),
                            DateUpdated = new DateTime(2026, 1, 15, 17, 1, 15, 600, DateTimeKind.Utc).AddTicks(2184),
                            Email = "system@local",
                            Name = "System",
                            Password = "changeme",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Address", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrder", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Mall", "Mall")
                        .WithMany("GroupOrders")
                        .HasForeignKey("MallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("GroupOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mall");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrderMember", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.GroupOrder", "GroupOrder")
                        .WithMany("GroupOrderMembers")
                        .HasForeignKey("GroupOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("GroupOrderMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GroupOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.MenuItem", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Order", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.GroupOrder", "GroupOrder")
                        .WithMany("Orders")
                        .HasForeignKey("GroupOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.OrderItem", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId");

                    b.HasOne("FoodDeliveryrestart.Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Payment", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Order", null)
                        .WithOne("Payment")
                        .HasForeignKey("FoodDeliveryrestart.Domain.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.PaymentMethod", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Restaurant", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Mall", "Mall")
                        .WithMany("Restaurants")
                        .HasForeignKey("MallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mall");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrder", b =>
                {
                    b.Navigation("GroupOrderMembers");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Mall", b =>
                {
                    b.Navigation("GroupOrders");

                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("GroupOrderMembers");

                    b.Navigation("GroupOrders");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
