// <auto-generated />
using System;
using FoodDeliveryrestart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDeliveryrestart.Migrations
{
    [DbContext(typeof(FoodDeliveryrestartContext))]
    [Migration("20260116041920_FixRestaurantImages")]
    partial class FixRestaurantImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c1a2b3c4-d5e6-4789-8901-234567890abc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "147f26b2-bd65-4e1b-9f42-0105f6f47f7f",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI1pft148y/+D0nNEiqZXkre5SYV0JQLcZjMipHdImt1B4hD9qEMWyDwyuJnXI5aAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7b5d1a90-05fa-48ab-9853-8b8f6be53c7f",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MallId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MallId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupOrder");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrderMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupOrderMember");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Mall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MallName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mall");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "4 Tampines Central 5, Singapore 529510",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3588),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3595),
                            MallName = "Tampines Mall",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1 HarbourFront Walk, Singapore 098585",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3596),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3597),
                            MallName = "Vivo City",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Address = "181 Orchard Rd, Singapore 238896",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3598),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3599),
                            MallName = "Orchard Central",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergens")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("CarbohydratesG")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FatG")
                        .HasColumnType("int");

                    b.Property<bool>("IsDairyFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHalal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNutFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProteinG")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergens = "Milk, Wheat",
                            Calories = 650,
                            CarbohydratesG = 45,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3883),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3884),
                            Description = "Signature burger topped with mozzarella and onions.",
                            FatG = 40,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Mozza Burger",
                            Price = 9.40m,
                            ProteinG = 30,
                            RestaurantId = 1,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 2,
                            Allergens = "Wheat",
                            Calories = 420,
                            CarbohydratesG = 30,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3887),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3887),
                            Description = "Hot dog topped with savory coney sauce.",
                            FatG = 25,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Coney Dog",
                            Price = 6.60m,
                            ProteinG = 15,
                            RestaurantId = 1,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 3,
                            Allergens = "",
                            Calories = 360,
                            CarbohydratesG = 48,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3890),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3890),
                            Description = "Crispy curly fries, perfect for sharing.",
                            FatG = 16,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = true,
                            ItemName = "Curly Fries",
                            Price = 3.60m,
                            ProteinG = 4,
                            RestaurantId = 1,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 4,
                            Allergens = "Milk",
                            Calories = 380,
                            CarbohydratesG = 52,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3893),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3894),
                            Description = "Classic root beer with vanilla ice cream.",
                            FatG = 12,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Root Beer Float",
                            Price = 3.50m,
                            ProteinG = 6,
                            RestaurantId = 1,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 5,
                            Allergens = "Wheat, Egg",
                            Calories = 750,
                            CarbohydratesG = 50,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3896),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3897),
                            Description = "Juicy beef patty with house sauce and fresh veg.",
                            FatG = 45,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Basic Burger",
                            Price = 20.50m,
                            ProteinG = 40,
                            RestaurantId = 2,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 6,
                            Allergens = "Fish, Wheat, Egg",
                            Calories = 620,
                            CarbohydratesG = 48,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3899),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3900),
                            Description = "Crispy fish fillet with tartar sauce.",
                            FatG = 30,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Fish Burger",
                            Price = 17.80m,
                            ProteinG = 30,
                            RestaurantId = 2,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 7,
                            Allergens = "Wheat",
                            Calories = 410,
                            CarbohydratesG = 46,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3902),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3903),
                            Description = "Golden battered onion rings.",
                            FatG = 20,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = true,
                            ItemName = "Onion Rings",
                            Price = 6.80m,
                            ProteinG = 4,
                            RestaurantId = 2,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 8,
                            Allergens = "",
                            Calories = 520,
                            CarbohydratesG = 55,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3905),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3906),
                            Description = "Fries tossed with truffle oil and seasoning.",
                            FatG = 28,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = true,
                            ItemName = "Truffle Fries",
                            Price = 8.00m,
                            ProteinG = 6,
                            RestaurantId = 2,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 9,
                            Allergens = "Wheat",
                            Calories = 480,
                            CarbohydratesG = 10,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3908),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3909),
                            Description = "Crispy fried chicken with gravy.",
                            FatG = 30,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Chickenjoy (1pc)",
                            Price = 5.70m,
                            ProteinG = 28,
                            RestaurantId = 3,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 10,
                            Allergens = "Wheat",
                            Calories = 560,
                            CarbohydratesG = 80,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3911),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3912),
                            Description = "Sweet-style spaghetti with hotdog slices.",
                            FatG = 16,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Jolly Spaghetti",
                            Price = 6.50m,
                            ProteinG = 18,
                            RestaurantId = 3,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 11,
                            Allergens = "Wheat, Egg",
                            Calories = 390,
                            CarbohydratesG = 35,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3914),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3915),
                            Description = "Classic burger with Jollibee signature dressing.",
                            FatG = 20,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Yumburger",
                            Price = 3.90m,
                            ProteinG = 18,
                            RestaurantId = 3,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 12,
                            Allergens = "Wheat",
                            Calories = 260,
                            CarbohydratesG = 34,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3918),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3918),
                            Description = "Crispy pie filled with peach-mango goodness.",
                            FatG = 12,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = true,
                            ItemName = "Peach Mango Pie",
                            Price = 1.90m,
                            ProteinG = 2,
                            RestaurantId = 3,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 13,
                            Allergens = "Wheat",
                            Calories = 320,
                            CarbohydratesG = 5,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3921),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3921),
                            Description = "KFC signature chicken with 11 herbs & spices.",
                            FatG = 22,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Original Recipe Chicken (1pc)",
                            Price = 4.45m,
                            ProteinG = 24,
                            RestaurantId = 4,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 14,
                            Allergens = "Wheat, Egg, Milk",
                            Calories = 550,
                            CarbohydratesG = 40,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3924),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3924),
                            Description = "Spicy chicken fillet burger with mayo.",
                            FatG = 30,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Zinger Burger",
                            Price = 7.50m,
                            ProteinG = 28,
                            RestaurantId = 4,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 15,
                            Allergens = "Milk",
                            Calories = 460,
                            CarbohydratesG = 50,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3927),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3927),
                            Description = "Fries topped with warm cheese sauce.",
                            FatG = 22,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Cheese Fries",
                            Price = 4.50m,
                            ProteinG = 8,
                            RestaurantId = 4,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 16,
                            Allergens = "Wheat",
                            Calories = 430,
                            CarbohydratesG = 18,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3930),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3930),
                            Description = "Bite-sized chicken chunks, crispy and juicy.",
                            FatG = 28,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Popcorn Chicken",
                            Price = 5.50m,
                            ProteinG = 26,
                            RestaurantId = 4,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 17,
                            Allergens = "Wheat, Egg, Milk",
                            Calories = 540,
                            CarbohydratesG = 47,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3933),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3933),
                            Description = "Two beef patties with special sauce and lettuce.",
                            FatG = 29,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Big Mac",
                            Price = 7.60m,
                            ProteinG = 25,
                            RestaurantId = 5,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 18,
                            Allergens = "Wheat, Egg",
                            Calories = 560,
                            CarbohydratesG = 44,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3936),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3936),
                            Description = "Spicy chicken burger with lettuce and mayo.",
                            FatG = 28,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "McSpicy",
                            Price = 7.50m,
                            ProteinG = 30,
                            RestaurantId = 5,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 19,
                            Allergens = "Fish, Wheat, Milk",
                            Calories = 390,
                            CarbohydratesG = 38,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3939),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3939),
                            Description = "Fish patty with tartar sauce and cheese.",
                            FatG = 18,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Filet-O-Fish",
                            Price = 7.45m,
                            ProteinG = 14,
                            RestaurantId = 5,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 20,
                            Allergens = "Wheat",
                            Calories = 240,
                            CarbohydratesG = 34,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3942),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3943),
                            Description = "Crispy pastry filled with warm apple cinnamon.",
                            FatG = 10,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = true,
                            ItemName = "Apple Pie",
                            Price = 2.50m,
                            ProteinG = 2,
                            RestaurantId = 5,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 21,
                            Allergens = "Wheat, Milk, Egg",
                            Calories = 720,
                            CarbohydratesG = 75,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3945),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3946),
                            Description = "Creamy pasta with bacon and parmesan.",
                            FatG = 36,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Carbonara",
                            Price = 14.90m,
                            ProteinG = 28,
                            RestaurantId = 6,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 22,
                            Allergens = "Wheat",
                            Calories = 620,
                            CarbohydratesG = 70,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3948),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3949),
                            Description = "Garlic, olive oil, chili flakes, and parsley.",
                            FatG = 28,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = true,
                            ItemName = "Aglio Olio",
                            Price = 12.90m,
                            ProteinG = 14,
                            RestaurantId = 6,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 23,
                            Allergens = "Wheat",
                            Calories = 740,
                            CarbohydratesG = 78,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3951),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3952),
                            Description = "Slow-cooked beef ragu with pasta.",
                            FatG = 34,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Beef Bolognese",
                            Price = 16.90m,
                            ProteinG = 32,
                            RestaurantId = 6,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 24,
                            Allergens = "Wheat, Milk",
                            Calories = 850,
                            CarbohydratesG = 80,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3954),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3955),
                            Description = "Layered pasta baked with meat sauce and cheese.",
                            FatG = 46,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Lasagna",
                            Price = 18.90m,
                            ProteinG = 36,
                            RestaurantId = 6,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 25,
                            Allergens = "Wheat, Milk",
                            Calories = 780,
                            CarbohydratesG = 90,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3957),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3958),
                            Description = "Tomato sauce, mozzarella, basil.",
                            FatG = 32,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Margherita Pizza",
                            Price = 12.90m,
                            ProteinG = 28,
                            RestaurantId = 7,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 26,
                            Allergens = "Wheat, Milk",
                            Calories = 920,
                            CarbohydratesG = 95,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3960),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3961),
                            Description = "Pepperoni, mozzarella, tomato base.",
                            FatG = 48,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Pepperoni Pizza",
                            Price = 14.90m,
                            ProteinG = 36,
                            RestaurantId = 7,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 27,
                            Allergens = "Wheat, Milk",
                            Calories = 880,
                            CarbohydratesG = 92,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3964),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3964),
                            Description = "Ham and pineapple with mozzarella.",
                            FatG = 44,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Hawaiian Pizza",
                            Price = 14.50m,
                            ProteinG = 34,
                            RestaurantId = 7,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 28,
                            Allergens = "Wheat, Milk",
                            Calories = 420,
                            CarbohydratesG = 48,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3967),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3967),
                            Description = "Toasted garlic bread slices.",
                            FatG = 18,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Garlic Bread",
                            Price = 5.50m,
                            ProteinG = 8,
                            RestaurantId = 7,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 29,
                            Allergens = "Shellfish",
                            Calories = 680,
                            CarbohydratesG = 85,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3970),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3970),
                            Description = "Thai-style fried rice with prawn and pineapple.",
                            FatG = 20,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = false,
                            IsVegan = false,
                            ItemName = "Pineapple Fried Rice (Prawn)",
                            Price = 9.48m,
                            ProteinG = 18,
                            RestaurantId = 8,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 30,
                            Allergens = "Shellfish, Fish",
                            Calories = 420,
                            CarbohydratesG = 18,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3973),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3973),
                            Description = "Creamy tom yum with seafood and herbs.",
                            FatG = 22,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = false,
                            IsVegan = false,
                            ItemName = "Creamy Tom Yum Soup (Seafood)",
                            Price = 12.90m,
                            ProteinG = 20,
                            RestaurantId = 8,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 31,
                            Allergens = "Shellfish, Peanuts",
                            Calories = 700,
                            CarbohydratesG = 88,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3976),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3976),
                            Description = "Stir-fried Thai noodles with prawn.",
                            FatG = 24,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = false,
                            IsVegan = false,
                            ItemName = "Pad Thai (Prawn)",
                            Price = 10.90m,
                            ProteinG = 20,
                            RestaurantId = 8,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 32,
                            Allergens = "",
                            Calories = 640,
                            CarbohydratesG = 80,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3979),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3979),
                            Description = "Basil chicken served with fragrant rice.",
                            FatG = 18,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Thai Basil Chicken Rice",
                            Price = 9.40m,
                            ProteinG = 22,
                            RestaurantId = 8,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 33,
                            Allergens = "Milk",
                            Calories = 280,
                            CarbohydratesG = 40,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3982),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3983),
                            Description = "Classic tart froyo cup (choose toppings).",
                            FatG = 8,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Signature Tart Frozen Yogurt Cup",
                            Price = 7.90m,
                            ProteinG = 4,
                            RestaurantId = 9,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 34,
                            Allergens = "Milk, Wheat",
                            Calories = 320,
                            CarbohydratesG = 44,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3985),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3986),
                            Description = "Creamy froyo with cookies flavour.",
                            FatG = 10,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Cookies & Cream Frozen Yogurt Cup",
                            Price = 8.50m,
                            ProteinG = 5,
                            RestaurantId = 9,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 35,
                            Allergens = "Soy",
                            Calories = 90,
                            CarbohydratesG = 10,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3988),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3989),
                            Description = "Add Biscoff spread as topping.",
                            FatG = 5,
                            IsDairyFree = true,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = true,
                            ItemName = "Biscoff Spread Topping",
                            Price = 1.50m,
                            ProteinG = 0,
                            RestaurantId = 9,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 36,
                            Allergens = "Wheat, Milk, Egg",
                            Calories = 140,
                            CarbohydratesG = 18,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3991),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3992),
                            Description = "Add chocolate brownie as topping.",
                            FatG = 7,
                            IsDairyFree = false,
                            IsHalal = true,
                            IsNutFree = true,
                            IsVegan = false,
                            ItemName = "Chocolate Fudge Brownie Topping",
                            Price = 1.80m,
                            ProteinG = 2,
                            RestaurantId = 9,
                            UpdatedBy = "Seed"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardHolderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CardType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardHolderName = "Seed User",
                            CardType = "Visa",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 4, 19, 19, 254, DateTimeKind.Utc).AddTicks(3438),
                            DateUpdated = new DateTime(2026, 1, 16, 4, 19, 19, 254, DateTimeKind.Utc).AddTicks(3439),
                            ExpiryMonth = 12,
                            ExpiryYear = 2026,
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CardHolderName = "Seed User",
                            CardType = "MasterCard",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 4, 19, 19, 254, DateTimeKind.Utc).AddTicks(3440),
                            DateUpdated = new DateTime(2026, 1, 16, 4, 19, 19, 254, DateTimeKind.Utc).AddTicks(3441),
                            ExpiryMonth = 10,
                            ExpiryYear = 2025,
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CardHolderName = "Seed User",
                            CardType = "AMEX",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 4, 19, 19, 254, DateTimeKind.Utc).AddTicks(3443),
                            DateUpdated = new DateTime(2026, 1, 16, 4, 19, 19, 254, DateTimeKind.Utc).AddTicks(3443),
                            ExpiryMonth = 6,
                            ExpiryYear = 2027,
                            UpdatedBy = "System",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusyLevel")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuisineType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationWithinMall")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MallId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperatingHours")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MallId");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusyLevel = 1,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3691),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3692),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/All_American_Food_Logo.svg/1024px-All_American_Food_Logo.svg.png",
                            LocationWithinMall = "1-24",
                            MallId = 1,
                            Name = "A&W",
                            OperatingHours = "10am-10pm",
                            Rating = 4.4m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 2,
                            BusyLevel = 2,
                            CreatedBy = "Seed",
                            CuisineType = "Western",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3694),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3695),
                            ImageUrl = "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1600&q=70",
                            LocationWithinMall = "1-68",
                            MallId = 1,
                            Name = "Burger Lab",
                            OperatingHours = "10am-10pm",
                            Rating = 4.6m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 3,
                            BusyLevel = 1,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3697),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3697),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Jollibee_Foods_Corporation_logo.png/1024px-Jollibee_Foods_Corporation_logo.png",
                            LocationWithinMall = "8-90",
                            MallId = 1,
                            Name = "Jollibee",
                            OperatingHours = "10am-10pm",
                            Rating = 4.7m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 4,
                            BusyLevel = 2,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3699),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3700),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/KFC_logo.svg/1024px-KFC_logo.svg.png",
                            LocationWithinMall = "8-89",
                            MallId = 1,
                            Name = "KFC",
                            OperatingHours = "24/7",
                            Rating = 4.2m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 5,
                            BusyLevel = 2,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3702),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3702),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/McDonald%27s_logo.svg/1024px-McDonald%27s_logo.svg.png",
                            LocationWithinMall = "8-88",
                            MallId = 1,
                            Name = "McDonald's",
                            OperatingHours = "24/7",
                            Rating = 4.3m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 6,
                            BusyLevel = 0,
                            CreatedBy = "Seed",
                            CuisineType = "Western",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3704),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3705),
                            ImageUrl = "https://images.unsplash.com/photo-1521389508051-d7ffb5dc8f6f?auto=format&fit=crop&w=1600&q=70",
                            LocationWithinMall = "1-67",
                            MallId = 1,
                            Name = "Pasta Corner",
                            OperatingHours = "24/7",
                            Rating = 4.1m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 7,
                            BusyLevel = 1,
                            CreatedBy = "Seed",
                            CuisineType = "Western Food",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3707),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3707),
                            ImageUrl = "https://images.unsplash.com/photo-1548365328-8b849e6a1e05?auto=format&fit=crop&w=1600&q=70",
                            LocationWithinMall = "1-66",
                            MallId = 1,
                            Name = "Pizza House",
                            OperatingHours = "24/7",
                            Rating = 4.5m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 8,
                            BusyLevel = 1,
                            CreatedBy = "Seed",
                            CuisineType = "Thai Food",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3709),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3710),
                            ImageUrl = "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1600&q=70",
                            LocationWithinMall = "1-25",
                            MallId = 1,
                            Name = "Sanook Kitchen",
                            OperatingHours = "10am-10pm",
                            Rating = 4.6m,
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 9,
                            BusyLevel = 0,
                            CreatedBy = "Seed",
                            CuisineType = "Dessert",
                            DateCreated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3712),
                            DateUpdated = new DateTime(2026, 1, 16, 12, 19, 19, 254, DateTimeKind.Local).AddTicks(3713),
                            ImageUrl = "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=1600&q=70",
                            LocationWithinMall = "1-23",
                            MallId = 1,
                            Name = "Yochi",
                            OperatingHours = "10am-10pm",
                            Rating = 4.8m,
                            UpdatedBy = "Seed"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 4, 19, 19, 254, DateTimeKind.Utc).AddTicks(2263),
                            DateUpdated = new DateTime(2026, 1, 16, 4, 19, 19, 254, DateTimeKind.Utc).AddTicks(2267),
                            Email = "system@local",
                            Name = "System",
                            Password = "changeme",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Address", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrder", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Mall", "Mall")
                        .WithMany("GroupOrders")
                        .HasForeignKey("MallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("GroupOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mall");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrderMember", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.GroupOrder", "GroupOrder")
                        .WithMany("GroupOrderMembers")
                        .HasForeignKey("GroupOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("GroupOrderMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GroupOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.MenuItem", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Order", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.GroupOrder", "GroupOrder")
                        .WithMany("Orders")
                        .HasForeignKey("GroupOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.OrderItem", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId");

                    b.HasOne("FoodDeliveryrestart.Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Payment", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Order", null)
                        .WithOne("Payment")
                        .HasForeignKey("FoodDeliveryrestart.Domain.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.PaymentMethod", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Restaurant", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Mall", "Mall")
                        .WithMany("Restaurants")
                        .HasForeignKey("MallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mall");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Data.FoodDeliveryrestartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrder", b =>
                {
                    b.Navigation("GroupOrderMembers");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Mall", b =>
                {
                    b.Navigation("GroupOrders");

                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("GroupOrderMembers");

                    b.Navigation("GroupOrders");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
