// <auto-generated />
using System;
using FoodDeliveryrestart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDeliveryrestart.Migrations
{
    [DbContext(typeof(FoodDeliveryrestartContext))]
    [Migration("20260109135028_AddRestaurantSeed")]
    partial class AddRestaurantSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MallId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MallId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupOrder");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrderMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupOrderMember");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Mall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MallName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mall");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "4 Tampines Central 5, Singapore 529510",
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7701),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7717),
                            MallName = "Tampines Mall",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1 HarbourFront Walk, Singapore 098585",
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7721),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7722),
                            MallName = "Vivo City",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 3,
                            Address = "181 Orchard Rd, Singapore 238896",
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7724),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7725),
                            MallName = "Orchard Central",
                            UpdatedBy = "Seed"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMethodId1")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentMethodId1");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardHolderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CardType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardHolderName = "Seed User",
                            CardType = "Visa",
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 9, 13, 50, 26, 445, DateTimeKind.Utc).AddTicks(7213),
                            DateUpdated = new DateTime(2026, 1, 9, 13, 50, 26, 445, DateTimeKind.Utc).AddTicks(7220),
                            ExpiryMonth = 12,
                            ExpiryYear = 2026,
                            UpdatedBy = "Seed",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CardHolderName = "Seed User",
                            CardType = "MasterCard",
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 9, 13, 50, 26, 445, DateTimeKind.Utc).AddTicks(7225),
                            DateUpdated = new DateTime(2026, 1, 9, 13, 50, 26, 445, DateTimeKind.Utc).AddTicks(7226),
                            ExpiryMonth = 10,
                            ExpiryYear = 2025,
                            UpdatedBy = "Seed",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CardHolderName = "Seed User",
                            CardType = "AMEX",
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 9, 13, 50, 26, 445, DateTimeKind.Utc).AddTicks(7231),
                            DateUpdated = new DateTime(2026, 1, 9, 13, 50, 26, 445, DateTimeKind.Utc).AddTicks(7232),
                            ExpiryMonth = 6,
                            ExpiryYear = 2027,
                            UpdatedBy = "Seed",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuisineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationWithinMall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MallId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MallId");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CuisineType = "Western",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7928),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7929),
                            LocationWithinMall = "1-67",
                            MallId = 1,
                            Name = "Pasta Corner",
                            OperatingHours = "24/7",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CuisineType = "Western Food",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7933),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7934),
                            LocationWithinMall = "1-66",
                            MallId = 1,
                            Name = "Pizza House",
                            OperatingHours = "24/7",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CuisineType = "Western",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7937),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7938),
                            LocationWithinMall = "1-68",
                            MallId = 1,
                            Name = "Burger Lab",
                            OperatingHours = "10am-10pm",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7941),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7942),
                            LocationWithinMall = "8-88",
                            MallId = 2,
                            Name = "McDonald's",
                            OperatingHours = "24/7",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7945),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7946),
                            LocationWithinMall = "8-89",
                            MallId = 2,
                            Name = "KFC",
                            OperatingHours = "24/7",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7950),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7951),
                            LocationWithinMall = "8-90",
                            MallId = 2,
                            Name = "Jollibee",
                            OperatingHours = "10am-10pm",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Seed",
                            CuisineType = "Dessert",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7954),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7955),
                            LocationWithinMall = "1-23",
                            MallId = 3,
                            Name = "Yochi",
                            OperatingHours = "10am-10pm",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "Seed",
                            CuisineType = "Fast Food",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7958),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7959),
                            LocationWithinMall = "1-24",
                            MallId = 3,
                            Name = "A&W",
                            OperatingHours = "10am-10pm",
                            UpdatedBy = "Seed"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "Seed",
                            CuisineType = "Thai Food",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7962),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(7963),
                            LocationWithinMall = "1-25",
                            MallId = 3,
                            Name = "Sanook Kitchen",
                            OperatingHours = "10am-10pm",
                            UpdatedBy = "Seed"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            DateCreated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(8380),
                            DateUpdated = new DateTime(2026, 1, 9, 21, 50, 26, 445, DateTimeKind.Local).AddTicks(8382),
                            Email = "seed@food.com",
                            Name = "Seed User",
                            Password = "Password123",
                            UpdatedBy = "Seed"
                        });
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Address", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrder", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Mall", "Mall")
                        .WithMany("GroupOrders")
                        .HasForeignKey("MallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("GroupOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mall");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrderMember", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.GroupOrder", "GroupOrder")
                        .WithMany("GroupOrderMembers")
                        .HasForeignKey("GroupOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("GroupOrderMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GroupOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.MenuItem", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Order", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.GroupOrder", "GroupOrder")
                        .WithMany("Orders")
                        .HasForeignKey("GroupOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.OrderItem", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId");

                    b.HasOne("FoodDeliveryrestart.Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Payment", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Order", null)
                        .WithOne("Payment")
                        .HasForeignKey("FoodDeliveryrestart.Domain.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.PaymentMethod", "PaymentMethods")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodDeliveryrestart.Domain.PaymentMethod", null)
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId1");

                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.PaymentMethod", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Restaurant", b =>
                {
                    b.HasOne("FoodDeliveryrestart.Domain.Mall", "Mall")
                        .WithMany("Restaurants")
                        .HasForeignKey("MallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mall");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.GroupOrder", b =>
                {
                    b.Navigation("GroupOrderMembers");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Mall", b =>
                {
                    b.Navigation("GroupOrders");

                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("FoodDeliveryrestart.Domain.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("GroupOrderMembers");

                    b.Navigation("GroupOrders");

                    b.Navigation("Orders");

                    b.Navigation("PaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
